name: Generate Unity ALF
on: [push]

jobs:
  generate_alf:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2022.3.20f1-android-3
    steps:
      - name: Generate ALF File
        run: /opt/unity/Editor/Unity -batchmode -nographics -createManualActivationFile -logfile || true
      - name: Upload ALF
        uses: actions/upload-artifact@v4
        with:
          name: Unity_ALF
          path: ./*.alf
