name: Get Unity Activation File
on: [push]

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v3
        with:
          unityVersion: 2022.3.20f1
      - name: Expose as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Unity_ALF
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
